services:

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_MODE=true
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami/kafka
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "kafka:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: techshop
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-write:
    build:
      context: ./api-write
    container_name: api_write
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    environment:
      - KAFKA_SERVER=kafka:9092
      - MONGO_URL=mongodb://mongo:27017/
    ports:
      - "8001:8000"

  api-read:
    build:
      context: ./api-read
    container_name: api_read
    depends_on:
      mysql:
        condition: service_started
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=techshop
    ports:
      - "8002:8000"

  sync-worker:
    build:
      context: ./sync-worker
    container_name: sync_worker
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
      mysql:
        condition: service_started
    environment:
      - KAFKA_SERVER=kafka:9092
      - MONGO_URL=mongodb://mongo:27017/
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=techshop

volumes:
  kafka_data:
  mongo_data:
  mysql_data:
